
# Agreement Configuration
DEFAULT_AGREEMENT_YEAR_RANGE = "2020 - 2025"

# Streamlit Configuration
STREAMLIT_PAGE_TITLE = "Bilingual RAG System"
STREAMLIT_PAGE_ICON = "🌍"
STREAMLIT_LAYOUT = "wide"

# Feature Flags
ENABLE_SOURCE_DISPLAY = True
ENABLE_LANGUAGE_STATS = True
ENABLE_CHAT_HISTORY = True
